Fix app crash due to date time attack on peer
When we are syncing between the peers, if any peer has invalid
year (less than 1400 or greater than 10000), boost will throw
exception on "net" thread (src/net.cpp/StartNode()):

************************
EXCEPTION: N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_9gregorian8bad_yearEEEEE
Year is out of valid range: 1400..10000
lux in Runaway exception

Solution:
Don't rethrow the exception on TraceThread() if current thread is
"net" thread

Signed-off-by: tran <nguyenhoangtran11@yahoo.com>